# create User
POST http://localhost:5000/api/users
Content-Type: application/json; charset=utf-8

{
    "username": "jeremy",
    "name": "Jeremy McKinnon",
    "email": "jeremy.mckinon@gmail.com",
    "password": "123456"
}
