# get all Users
# GET http://localhost:5000/user

# get Users from page 1  with 10 items per page
GET http://localhost:5000/user
?page=1&size=10


# get Users from page 1 with 2 items per page
# GET http://localhost:5000/user
# ?page=1&size=2


# get Users from page 2 with 2 items per page
GET http://localhost:5000/user
?page=2&size=2
